Fix/modalchart resolutions
southworkscom/cognitive-services-personalizer-samples pull request #109
Opened 2019-07-22 18:09 UTC by marianstdt

## Purpose

* Divide modal in two rows 
* Fix scaling for mobile and 4K

4k
![image](https://user-images.githubusercontent.com/4763385/61654171-38396900-ac92-11e9-80c9-afc6ee597bd9.png)
![image](https://user-images.githubusercontent.com/4763385/61654312-8484a900-ac92-11e9-8ea3-940df0535206.png)

Pixel 2
![image](https://user-images.githubusercontent.com/4763385/61654279-759df680-ac92-11e9-88a3-3353827910c0.png)

2019-07-22 21:10 UTC, ParadoxARG commented
It's still broken when loading on mobile but it fixes if you swap to a bigger screen and then back to mobile. We need to find if there is a way to fix the graph rendering or take the decision to hide the graph for mobile. Do we really need the graph for mobile? Does it add any value?

2019-07-24 13:54 UTC, marianstdt commented
> It's still broken when loading on mobile but it fixes if you swap to a bigger screen and then back to mobile. We need to find if there is a way to fix the graph rendering or take the decision to hide the graph for mobile. Do we really need the graph for mobile? Does it add any value?

We should merge this as it has important changes for the modal and create a new PR to address the fix for mobile, once I'm again in the organization I'll push a fix for the conflicts.

2019-07-24 14:19 UTC, ParadoxARG requested changes

2019-07-24 14:19 UTC, ParadoxARG commented on demos/PersonalizerBusinessDemo/PersonalizerBusinessDemo/Views/Home/Index.cshtml
> +
nit

2019-07-24 14:57 UTC, kbrons approved these changes

2019-07-24 14:58 UTC, merged