Move style tags to site stylesheet
southworkscom/cognitive-services-personalizer-samples pull request #119
Opened 2019-07-23 16:43 UTC by lucaasrojas

- Style tags in html files were been moved to site.css stylesheet.
In case of the site background I had to add to it an ID to set the gradient color.

2019-07-23 20:30 UTC, ParadoxARG approved these changes
LGTM

2019-07-23 20:48 UTC, kbrons requested changes

2019-07-23 20:48 UTC, kbrons commented on demos/PersonalizerBusinessDemo/PersonalizerBusinessDemo/wwwroot/css/site.css
> +body {
This change is affecting both Layout and ArticleLayout. Make sure it only affects the latter.

2019-07-24 18:45 UTC, kbrons approved these changes

2019-07-24 18:45 UTC, merged