[WIP] Replace tournament context variables with new variables
southworkscom/cognitive-services-personalizer-samples pull request #149
Opened 2019-07-26 16:34 UTC by lucaasrojas

- Remove Ongoing Tournament
- Add Costs and Additionals context variables

2019-07-26 20:45 UTC, ParadoxARG requested changes

2019-07-26 20:45 UTC, ParadoxARG commented on demos/PersonalizerTravelAgencyDemo/PersonalizerTravelAgencyDemo/Models/UserContext.cs
>          public bool UseTextAnalytics { get; set; }
We should remove Referrer and UseTextAnalytics.

2019-07-26 20:45 UTC, ParadoxARG commented on demos/PersonalizerTravelAgencyDemo/PersonalizerTravelAgencyDemo/wwwroot/js/demo.js
>      deviceSelectEle.addEventListener('change', (event) => {
Remove the second `null`(tournament) from updateContext in `deviceSelectEle` listener and `UseUserAgentEle` listener

2019-07-26 21:25 UTC, ParadoxARG requested changes

2019-07-26 21:25 UTC, ParadoxARG commented on demos/PersonalizerTravelAgencyDemo/PersonalizerTravelAgencyDemo/Controllers/MetadataController.cs
>          public JsonResult Actions(bool useTextAnalytics)
Remove parameter

2019-07-26 21:25 UTC, ParadoxARG commented on demos/PersonalizerTravelAgencyDemo/PersonalizerTravelAgencyDemo/Repositories/ActionsRepository.cs
remove all the _ActionsWithTextTanalytics logic

2019-07-26 21:25 UTC, ParadoxARG commented on demos/PersonalizerTravelAgencyDemo/PersonalizerTravelAgencyDemo/wwwroot/js/demo.js
>  };
Remove referrers and actions listeners and logic

2019-07-26 21:55 UTC, ParadoxARG requested changes

2019-07-26 21:55 UTC, ParadoxARG commented on demos/PersonalizerTravelAgencyDemo/PersonalizerTravelAgencyDemo/wwwroot/js/demo.js
> +function updateContext( device, currentCost, currentAdditionals, removeUserAgent, userAgent) {
Make all the calls consistent with the new firm

2019-07-29 19:45 UTC, ParadoxARG requested changes

2019-07-29 19:45 UTC, ParadoxARG commented on demos/PersonalizerTravelAgencyDemo/PersonalizerTravelAgencyDemo/wwwroot/js/demo.js
> +            updateContext(null, null, false, userAgent);
missing a null parameter

2019-07-29 19:45 UTC, ParadoxARG commented on demos/PersonalizerTravelAgencyDemo/PersonalizerTravelAgencyDemo/wwwroot/js/demo.js
> +            updateContext(null, null, true, null);
Missing a null parameter

2019-07-29 19:52 UTC, ParadoxARG approved these changes
LGTM

2019-07-29 21:04 UTC, kbrons approved these changes

2019-07-29 21:04 UTC, merged